### ISSUE TITLE
Skip Controls Not working with latest Spotify Update Mac

### ISSUE THREAD

**Issue by xiaogwu** [jguice/mac-bt-headset-fix#25]
I think the Mac Spotify Desktop Client was updated today and now the skip control is not be recognized.  The Play/Stop/Pause seems to still work.

**Comment by jguice** [comment]
Hi, try a press-and-hold on the next/prev buttons. :)

**Comment by xiaogwu** [comment]
That seems to work however it doesn't fit with normal user paradigms.  Most of the time it will skip two songs cause I'm holding it too long maybe.  My next/prev button is actually more of slider (H800 Logitech)  You would think holding it would be fast-forward.  IMO.

It it hard to just recognize the single next/prev click/select event?

**Comment by jguice** [comment]
The app already recognizes next, prev, fast-forward, and rewind.  The problem seems to be that the behavior is mapped inconsistently to headphone buttons. :)

I can swap the fast-forward/next and rewind/prev button mappings so a single press will skip tracks and a press-and-hold will fast-forward and rewind.

Maybe that will be an expected user experience for the majority of people (though it will probably confuse some folks who have difference mappings and are already used to the current behavior).  I'll make that change shortly and update the readme.  Thanks!

**Comment by jguice** [comment]
Ok, try the [latest build](https://s3-us-west-2.amazonaws.com/jguice/mac-bt-headset-fix/Spotify+Bluetooth+Headset+Listener.zip) please and let me know how it goes. (for my notes: 951834402bb05108f4c8ceca6984dd15718ce8ea)

**Comment by xiaogwu** [comment]
Works as expected. Thank you!

**Comment by jguice** [comment]
Cool.  Thanks for the feedback and help testing! :smile:
